Repository NOAA-EMC/RDASApp, pull requests merged in 2024-10, with the labels that each got.

#184 Update ctests to include more obs types for more realistic testing
  fix/expr_data/mpas_2024052700/obs_ctest
  rrfs-test/CMakeLists.txt
  rrfs-test/obs/msonet_singleob_airTemperature.nc4
  rrfs-test/scripts/link_mpasjedi_expr.sh
  rrfs-test/scripts/setup_experiment.sh
  rrfs-test/scripts/setup_experiment.sh.new
  rrfs-test/testinput/msonet_airTemperature.yaml
  rrfs-test/testinput/msonet_singleob_airTemperature_fv3jedi.yaml
  rrfs-test/testinput/msonet_singleob_airTemperature_mpasjedi.yaml
  rrfs-test/testinput/rrfs_fv3jedi_hyb_2022052619.yaml
  rrfs-test/testinput/rrfs_fv3jedi_letkf_2022052619.yaml
  rrfs-test/testinput/rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
  rrfs-test/testinput/rrfs_mpasjedi_2024052700_getkf_observer.yaml
  rrfs-test/testinput/rrfs_mpasjedi_2024052700_getkf_solver.yaml
  rrfs-test/testinput_expr/namelist.atmosphere
  rrfs-test/testinput_expr/rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
  rrfs-test/testinput_expr/rrfs_mpasjedi_2024052700_bumploc.yaml
  rrfs-test/testinput_expr/rrfs_mpasjedi_2024052700_getkf.yaml
  rrfs-test/testinput_expr/rrfs_mpasjedi_2024052700_getkf_observer.yaml
  rrfs-test/testinput_expr/rrfs_mpasjedi_2024052700_getkf_solver.yaml
  rrfs-test/testinput_expr/rrfs_mpasjedi_2024052700_letkf.yaml
  rrfs-test/testinput_expr/streams.atmosphere
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-solver.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf.ref
  rrfs-test/testoutput/rrfs-mpasjedi-letkf.ref
  rrfs-test/validated_yamls/gen_yaml.sh
  rrfs-test/validated_yamls/gen_yaml_ctest.sh
  rrfs-test/validated_yamls/templates/basic_config/fv3jedi_hyb3denvar.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_3dvar.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_en3dvar.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_observer.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_solver.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_specificHumidity_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_uv_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_130.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_131.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_135.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_specificHumidity_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_uv_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_uv_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_uv_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_uv_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp_qc_bc.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_airTemperature_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_specificHumidity_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_stationPressure_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_uv_288.yaml
  ush/run_rrfs_tests.sh
Labels: Passed_hera, Passed_jet, Passed_hercules

#196 port RDASApp to Gaea
  README.md
  build.sh
  docs/build_and_test.md
  modulefiles/EVA/gaeaC5.lua
  modulefiles/EVA/gaeaC6.lua
  modulefiles/RDAS/gaea.intel.lua
  rrfs-test/scripts/templates/mpasjedi_expr/run_bump.sh
  rrfs-test/scripts/templates/mpasjedi_expr/run_jedi.sh
  ush/detect_machine.sh
  ush/init.sh
  ush/load_eva.sh
Labels: Passed_hercules

#207 Add bufr2ioda ctest
  rrfs-test/CMakeLists.txt
  rrfs-test/testinput/rrfs_bufr2ioda_msonet.yaml
  rrfs-test/ush/iodaconv_comp_rrfs.sh
  ush/run_rrfs_tests.sh
Labels: running_hercules, Passed_hera, Passed_jet
