Repository NOAA-EMC/RDASApp, pull requests merged in 2025-03, with the labels that each got.

#302 reorder sections in MPASJEDI getkf yaml files to be consistent with en3dvar ones
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_observer.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_solver.yaml
Labels: Passed_hera

#301 change the leftover `@OBSFILE@` in observers to be consistent with others
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_281.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_stationPressure_120.yaml
Labels: Passed_hera

#305 add yaml_cat_together.py to generate MPASJEDI super YAML files for `YAML_GEN_METHOD=1` in rrfs-workflow
  .gitignore
  rrfs-test/validated_yamls/templates/yaml_cat_together.py
Labels: Passed_jet

#318 Update libxpm and rocoto versions on Hercules
  modulefiles/RDAS/hera.gnu.lua
  modulefiles/RDAS/hera.intel.lua
  modulefiles/RDAS/hercules.intel.lua
  modulefiles/RDAS/jet.gnu.lua
  modulefiles/RDAS/jet.intel.lua
  modulefiles/RDAS/orion.intel.lua
Labels: Passed_hercules

#322 Update libxpm on Orion
  modulefiles/RDAS/orion.intel.lua
Labels: Passed_hercules

#298 Generate ctest yamls when RDASApp is built to better sync ctests with templates
  .gitignore
  build.sh
  fix/expr_data/fv3_2024052700/data/obs
  fix/expr_data/mpas_2024052700/obs
  rrfs-test/example_yamls/namelist.atmosphere
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_Hybrid.yaml
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_bumploc.yaml
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_getkf.yaml
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_getkf_observer.yaml
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_getkf_solver.yaml
  rrfs-test/example_yamls/rrfs_mpasjedi_2024052700_letkf.yaml
  rrfs-test/example_yamls/streams.atmosphere
  rrfs-test/scripts/link_mpasjedi_expr.sh
  rrfs-test/testinput/rrfs_fv3jedi_2024052700_Ens3Dvar.yaml
  rrfs-test/testinput/rrfs_fv3jedi_2024052700_getkf_observer.yaml
  rrfs-test/testinput/rrfs_fv3jedi_2024052700_getkf_solver.yaml
  rrfs-test/testinput/rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
  rrfs-test/testinput/rrfs_mpasjedi_2024052700_getkf_observer.yaml
  rrfs-test/testinput/rrfs_mpasjedi_2024052700_getkf_solver.yaml
  rrfs-test/testoutput/rrfs-fv3jedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-solver.ref
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-solver.ref
  rrfs-test/ush/iodaconv_comp_rrfs.sh
  rrfs-test/validated_yamls/commentQC.py
  rrfs-test/validated_yamls/gen_yaml.sh
  rrfs-test/validated_yamls/gen_yaml_ctest.sh
  rrfs-test/validated_yamls/gen_yaml_fv3jedi_ctest.sh
  rrfs-test/validated_yamls/gen_yaml_mpasjedi_ctest.sh
  rrfs-test/validated_yamls/templates/obtype_config/amsua_n19.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_n20.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp_qc_bc.yaml
  rrfs-test/validated_yamls/templates/obtype_config/rassda_airTemperature_126.yaml
  rrfs-test/validated_yamls/templates/obtype_config/vadwnd_winds_224.yaml
Labels: Passed_hera, Passed_jet, Passed_hercules

#314 bugfix to handle missing QualityMarkers in jediyaml and removes duplicate action key.
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_281.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_287.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_stationPressure_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_220.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_specificHumidity_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_winds_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_130.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_131.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_135.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_specificHumidity_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_airTemperature_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_specificHumidity_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_stationPressure_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_winds_288.yaml
  rrfs-test/validated_yamls/templates/obtype_config/proflr_winds_227.yaml
  rrfs-test/validated_yamls/templates/obtype_config/rassda_airTemperature_126.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_280.yaml
  rrfs-test/validated_yamls/templates/obtype_config/vadwnd_winds_224.yaml
Labels: Passed_hera, Passed_jet, Passed_hercules

#337 Quick bugfix to create super yamls before `expr` directories
  build.sh
  ush/update_ctest_inputs.sh
  ush/update_ctest_refs.sh
Labels: Passed_hera, Passed_jet, Passed_hercules

#324 ADD ZTD bufr2ioda python tool and jedi yaml (updated)
  rrfs-test/IODA/python/bufr2ioda.json
  rrfs-test/IODA/python/bufr2ioda_ztd.py
  rrfs-test/testoutput/rrfs-fv3jedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-solver.ref
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-solver.ref
  rrfs-test/validated_yamls/gen_yaml_ctest.sh
  rrfs-test/validated_yamls/templates/obtype_config/gnss_zenithTotalDelay.yaml
Labels: Passed_hera, Passed_jet, Failed_hercules

#329 Add abi_g16 & abi_g18 YAML files into templates
  rrfs-test/testoutput/rrfs-fv3jedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-solver.ref
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-solver.ref
  rrfs-test/validated_yamls/commentQC.py
  rrfs-test/validated_yamls/gen_yaml_ctest.sh
  rrfs-test/validated_yamls/templates/obtype_config/abi_g16.yaml
  rrfs-test/validated_yamls/templates/obtype_config/abi_g18.yaml
Labels: Passed_hera, Failed_hercules

#346 Increase ctest tolerance and fix ctest error on Hercules
  rrfs-test/CMakeLists.txt
  rrfs-test/validated_yamls/templates/basic_config/fv3jedi_en3dvar.yaml
  rrfs-test/validated_yamls/templates/basic_config/fv3jedi_getkf_observer.yaml
  rrfs-test/validated_yamls/templates/basic_config/fv3jedi_getkf_solver.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_en3dvar.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_observer.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_solver.yaml
Labels: Passed_hera, Passed_jet, Passed_hercules
