Repository NOAA-EMC/RDASApp, pull requests merged in 2025-02, with the labels that each got.

#263 change the spack-stack location on Hera
  modulefiles/RDAS/hera.intel.lua
Labels: Passed_hera

#264 quick fix - change 'uv_233' to 'winds_233' in gen_yaml files
  rrfs-test/validated_yamls/gen_yaml.sh
  rrfs-test/validated_yamls/gen_yaml_fv3jedi_ctest.sh
  rrfs-test/validated_yamls/gen_yaml_mpasjedi_ctest.sh
Labels: Passed_hera, Passed_jet

#277 add GNU compiling capability for Hera/Jet
  modulefiles/RDAS/hera.gnu.lua
  modulefiles/RDAS/jet.gnu.lua
Labels: Passed_hera, Passed_jet

#288 Set ctests to use 4 nodes on Hercules
  rrfs-test/CMakeLists.txt
Labels: Passed_hercules

#290 use consistent fixed prescribed ioda file names at the DA runtime
  rrfs-test/CMakeLists.txt
  rrfs-test/scripts/link_fv3jedi_expr.sh
  rrfs-test/scripts/link_mpasjedi_expr.sh
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_287.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_220.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_specificHumidity_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_winds_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_130.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_131.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_135.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_specificHumidity_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/amsua_n19.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp_qc_bc.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_airTemperature_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_specificHumidity_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_stationPressure_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_winds_288.yaml
  rrfs-test/validated_yamls/templates/obtype_config/proflr_winds_227.yaml
  rrfs-test/validated_yamls/templates/obtype_config/rassda_airTemperature_126.yaml
  rrfs-test/validated_yamls/templates/obtype_config/vadwnd_winds_224.yaml
Labels: Passed_jet
