Repository NOAA-EMC/RDASApp, pull requests merged in 2025-04, with the labels that each got.

#355 add the "missing file action" key into yaml files to handle possible missing ioda files in operation
  rrfs-test/validated_yamls/templates/obtype_config/abi_g16.yaml
  rrfs-test/validated_yamls/templates/obtype_config/abi_g18.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_281.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_287.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_132.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_132.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_stationPressure_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_220.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_232.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_specificHumidity_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_winds_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_130.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_131.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_135.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_specificHumidity_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/amsua_n19.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_n20.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp.yaml
  rrfs-test/validated_yamls/templates/obtype_config/gnss_zenithTotalDelay.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_airTemperature_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_specificHumidity_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_stationPressure_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_winds_288.yaml
  rrfs-test/validated_yamls/templates/obtype_config/proflr_winds_227.yaml
  rrfs-test/validated_yamls/templates/obtype_config/rassda_airTemperature_126.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_280.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_282.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/vadwnd_winds_224.yaml
Labels: Passed_hera

#364 Minor updated indent of ztd yaml
  rrfs-test/validated_yamls/templates/obtype_config/gnss_zenithTotalDelay.yaml
Labels: Passed_hera, Passed_jet

#326 Phase 2&3 validation: prepbufr
  rrfs-test/testoutput/rrfs-fv3jedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/validated_yamls/commentQC.py
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_281.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_287.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_132.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_132.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_stationPressure_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_220.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_232.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_specificHumidity_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_winds_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_130.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_131.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_135.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_specificHumidity_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_airTemperature_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_specificHumidity_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_stationPressure_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_winds_288.yaml
  rrfs-test/validated_yamls/templates/obtype_config/proflr_winds_227.yaml
  rrfs-test/validated_yamls/templates/obtype_config/rassda_airTemperature_126.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_280.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_282.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/vadwnd_winds_224.yaml
Labels: Passed_hera, Passed_jet, Passed_hercules

#368 [feature & bugfix] Add passivate options and fixes associated with ctests
  rrfs-test/validated_yamls/gen_yaml_ctest.sh
  rrfs-test/validated_yamls/templates/obtype_config/abi_g16.yaml
  rrfs-test/validated_yamls/templates/obtype_config/abi_g18.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_airTemperature_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_specificHumidity_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_181.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_stationPressure_187.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_281.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_287.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_airTemperature_132.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_specificHumidity_132.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_stationPressure_120.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_220.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_232.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_airTemperature_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_specificHumidity_133.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_winds_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_130.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_131.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_airTemperature_135.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_specificHumidity_134.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/amsua_n19.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_n20.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp.yaml
  rrfs-test/validated_yamls/templates/obtype_config/gnss_zenithTotalDelay.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_airTemperature_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_specificHumidity_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_stationPressure_188.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_winds_288.yaml
  rrfs-test/validated_yamls/templates/obtype_config/proflr_winds_227.yaml
  rrfs-test/validated_yamls/templates/obtype_config/rassda_airTemperature_126.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_airTemperature_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_specificHumidity_183.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_180.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_stationPressure_182.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_280.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_282.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/vadwnd_winds_224.yaml
Labels: Passed_hera, Passed_jet, Passed_hercules

#351 Add the YAML linter and modify YAML files accordingly in order to pass the linting.
  .github/workflows/linters.yaml
  .github/workflows/norms.yaml.bak
  .github/workflows/unittests.yaml.bak
  .yamllint
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_observer.yaml
  rrfs-test/validated_yamls/templates/basic_config/mpasjedi_getkf_solver.yaml
  rrfs-test/validated_yamls/templates/obtype_config/abi_g16.yaml
  rrfs-test/validated_yamls/templates/obtype_config/abi_g18.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_281.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_284.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpsfc_winds_287.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_220.yaml
  rrfs-test/validated_yamls/templates/obtype_config/adpupa_winds_232.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircar_winds_233.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_230.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_231.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_234.yaml
  rrfs-test/validated_yamls/templates/obtype_config/aircft_winds_235.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_n20.yaml
  rrfs-test/validated_yamls/templates/obtype_config/atms_npp.yaml
  rrfs-test/validated_yamls/templates/obtype_config/gnss_zenithTotalDelay.yaml
  rrfs-test/validated_yamls/templates/obtype_config/msonet_winds_288.yaml
  rrfs-test/validated_yamls/templates/obtype_config/proflr_winds_227.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_282.yaml
  rrfs-test/validated_yamls/templates/obtype_config/sfcshp_winds_284.yaml
  ush/linter_yamlcheck.sh
  ush/remove_trailing_whitespace
Labels: Passed_hera

#369 Add a dummy variable for `ObsError/specificHumidity` to prevent empty observation errors during the GETKF solver
  fix/expr_data/fv3_2024052700/data/obs
  fix/expr_data/mpas_2024052700/obs
  rrfs-test/IODA/yaml/prepbufr_adpsfc.yaml
  rrfs-test/IODA/yaml/prepbufr_adpupa.yaml
  rrfs-test/IODA/yaml/prepbufr_aircar.yaml
  rrfs-test/IODA/yaml/prepbufr_aircft.yaml
  rrfs-test/IODA/yaml/prepbufr_msonet.yaml
  rrfs-test/IODA/yaml/prepbufr_proflr.yaml
  rrfs-test/IODA/yaml/prepbufr_rassda.yaml
  rrfs-test/IODA/yaml/prepbufr_satwnd.yaml
  rrfs-test/IODA/yaml/prepbufr_sfcshp.yaml
  rrfs-test/IODA/yaml/prepbufr_vadwnd.yaml
  rrfs-test/testoutput/rrfs-fv3jedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-solver.ref
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-solver.ref
Labels: Passed_hera, Passed_hercules, Failed_jet

#376 Adding an obs space YAML for ATMS N21
  rrfs-test/testoutput/rrfs-fv3jedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-fv3jedi-getkf-solver.ref
  rrfs-test/testoutput/rrfs-mpasjedi-ens3dvar.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-observer.ref
  rrfs-test/testoutput/rrfs-mpasjedi-getkf-solver.ref
  rrfs-test/validated_yamls/gen_yaml_ctest.sh
  rrfs-test/validated_yamls/templates/obtype_config/atms_n21.yaml
Labels: Passed_hera, Passed_hercules
